version: '3'

services:
  jojomoodbot:
    image: azimanov/pocketpythonbot:latest
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
    environment:
      TELEGRAM_BOT_TOKEN: "???"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 --scope myscope --cleanup
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
