name: Main workflow

on: [ push ]

jobs:
  doing_main_job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: Check that everything is OK
      run: |
        echo 'everything is ok'

    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
    - name: Building and push docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dxtvzw/pocketpythonbot:latest
